'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('products', [
      {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
        {
        name: 'Điện Thoại Samsung A34 5G 8GB/128GB - Hàng Chính Hãng',
        description: 'Nothing',
        price: 8490000.0,
        createdAt: new Date(),
        updatedAt: new Date(),
        sellerId: 3,
        },
    ]);
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
